// Config.swift
// Firebase client configuration, injected at build time.
//
// Values are never stored in the repository. They live in `FirebaseConfig.plist`,
// generated by `Config/generate-firebase-config.sh` from environment variables
// (Codemagic in CI, a local copy of
// `Config/Firebase/FirebaseConfig.plist.example` for developers) and copied into
// the app bundle by the `Copy Firebase configuration` build phase.
//
// When the file is absent every value is empty, `Backend.isConfigured` returns
// false and the app stays in local demo mode instead of failing at launch.

import Foundation
import OSLog

enum Config {
    static let FIREBASE_API_KEY = value(for: "FIREBASE_API_KEY")
    static let FIREBASE_APP_ID = value(for: "FIREBASE_APP_ID")
    static let FIREBASE_PROJECT_ID = value(for: "FIREBASE_PROJECT_ID")
    static let FIREBASE_GCM_SENDER_ID = value(for: "FIREBASE_GCM_SENDER_ID")
    static let FIREBASE_STORAGE_BUCKET = value(for: "FIREBASE_STORAGE_BUCKET")

    static let allValues: [String: String] = [
        "FIREBASE_API_KEY": FIREBASE_API_KEY,
        "FIREBASE_APP_ID": FIREBASE_APP_ID,
        "FIREBASE_PROJECT_ID": FIREBASE_PROJECT_ID,
        "FIREBASE_GCM_SENDER_ID": FIREBASE_GCM_SENDER_ID,
        "FIREBASE_STORAGE_BUCKET": FIREBASE_STORAGE_BUCKET,
    ]

    private static let logger = Logger(subsystem: "com.assodarts.app", category: "Config")

    private static let values: [String: String] = {
        guard let path = Bundle.main.path(forResource: "FirebaseConfig", ofType: "plist"),
              let raw = NSDictionary(contentsOfFile: path) as? [String: Any]
        else {
            logConfigurationIsMissing()
            return [:]
        }
        let loaded = raw.compactMapValues { $0 as? String }.filter { !$0.value.isEmpty }
        if loaded.isEmpty {
            logConfigurationIsMissing()
        }
        return loaded
    }()

    private static func logConfigurationIsMissing() {
        logger.error(
            """
            No Firebase credentials in FirebaseConfig.plist: the app runs in demo mode. \
            Run Config/generate-firebase-config.sh, or copy \
            Config/Firebase/FirebaseConfig.plist.example and fill it in, before building.
            """
        )
    }

    private static func value(for key: String) -> String {
        values[key] ?? ""
    }
}

