// Config.swift - Auto-generated at build time
// Virtual read-only view of public environment variables available to Swift code.
//
// The string literals below are INTENTIONALLY EMPTY in source control —
// the real values are injected at iOS build time. Do not edit this file
// to add values, and do not inspect it to discover env values (you will
// only ever see ""). To find a value at agent-time, look up the env name
// in the project's .env file or in the Rork agent's environment listing.

import Foundation

enum Config {
    static let FIREBASE_API_KEY = ""
    static let FIREBASE_APP_ID = ""
    static let FIREBASE_PROJECT_ID = ""
    static let FIREBASE_GCM_SENDER_ID = ""
    static let FIREBASE_STORAGE_BUCKET = ""

    static let allValues: [String: String] = [
        "FIREBASE_API_KEY": FIREBASE_API_KEY,
        "FIREBASE_APP_ID": FIREBASE_APP_ID,
        "FIREBASE_PROJECT_ID": FIREBASE_PROJECT_ID,
        "FIREBASE_GCM_SENDER_ID": FIREBASE_GCM_SENDER_ID,
        "FIREBASE_STORAGE_BUCKET": FIREBASE_STORAGE_BUCKET,
    ]
}
