sonar.organization=floriangiral
sonar.projectKey=floriangiral_rork-assodarts
sonar.projectName=Assodarts
sonar.sources=ios-assodarts/Assodarts,backend/functions/src
sonar.tests=ios-assodarts/AssodartsTests,ios-assodarts/AssodartsUITests
sonar.test.inclusions=backend/functions/src/**/*.test.ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/Config.swift,backend/types.ts,backend/functions/lib/**,backend/functions/coverage/**
sonar.coverage.exclusions=**/Config.swift,**/*View.swift,backend/functions/src/index.ts,backend/functions/src/**/*.test.ts
sonar.coverageReportPaths=ios-coverage.xml
sonar.javascript.lcov.reportPaths=backend-coverage.lcov
