sonar.organization=floriangiral
sonar.projectKey=floriangiral_rork-assodarts
sonar.projectName=Assodarts
sonar.sources=ios-assodarts/Assodarts,backend/functions
sonar.tests=ios-assodarts/AssodartsTests,ios-assodarts/AssodartsUITests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/Config.swift,backend/types.ts
sonar.coverage.exclusions=**/Config.swift,**/*View.swift,backend/functions/stripe-return/index.ts